import React, { useState, useMemo, useEffect } from "react";
import Autocomplete from "@mui/material/Autocomplete";
import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";
import { FieldCorrection } from '../../../types/ai';
import { InlineFieldCorrection } from '../ai/InlineFieldCorrection';

/**
 * Comprehensive list of top global universities (QS World Rankings, Times Higher Education)
 * plus all major Iranian universities.
 * Organized by region for maintainability.
 */

// Top US Universities
const US_UNIVERSITIES = [
  "Massachusetts Institute of Technology (MIT)",
  "Stanford University",
  "Harvard University",
  "California Institute of Technology (Caltech)",
  "University of Chicago",
  "Princeton University",
  "Yale University",
  "Columbia University",
  "University of Pennsylvania",
  "Cornell University",
  "Duke University",
  "Northwestern University",
  "Johns Hopkins University",
  "Brown University",
  "Dartmouth College",
  "Vanderbilt University",
  "Rice University",
  "University of Notre Dame",
  "Washington University in St. Louis",
  "Georgetown University",
  "Emory University",
  "University of Southern California (USC)",
  "Carnegie Mellon University",
  "University of California, Berkeley (UC Berkeley)",
  "University of California, Los Angeles (UCLA)",
  "University of California, San Diego (UCSD)",
  "University of California, Santa Barbara (UCSB)",
  "University of California, Davis (UC Davis)",
  "University of California, Irvine (UCI)",
  "University of California, Santa Cruz (UCSC)",
  "University of California, Riverside (UCR)",
  "University of Michigan",
  "University of Virginia",
  "University of North Carolina at Chapel Hill",
  "Georgia Institute of Technology (Georgia Tech)",
  "University of Texas at Austin",
  "University of Wisconsin-Madison",
  "University of Illinois Urbana-Champaign",
  "Pennsylvania State University",
  "Ohio State University",
  "University of Washington",
  "University of Florida",
  "New York University (NYU)",
  "Boston University",
  "Boston College",
  "Northeastern University",
  "Tufts University",
  "Brandeis University",
  "University of Rochester",
  "Case Western Reserve University",
  "University of Miami",
  "Tulane University",
  "University of Pittsburgh",
  "Purdue University",
  "Indiana University Bloomington",
  "Michigan State University",
  "University of Minnesota",
  "University of Maryland, College Park",
  "Rutgers University",
  "University of Colorado Boulder",
  "University of Arizona",
  "Arizona State University",
  "University of Utah",
  "University of Iowa",
  "University of Kansas",
  "University of Nebraska-Lincoln",
  "University of Oregon",
  "Oregon State University",
  "University of Connecticut",
  "University of Massachusetts Amherst",
  "George Washington University",
  "American University",
  "Syracuse University",
  "University of Delaware",
  "Virginia Tech",
  "North Carolina State University",
  "University of South Carolina",
  "Clemson University",
  "University of Georgia",
  "Florida State University",
  "University of Central Florida",
  "Texas A&M University",
  "University of Houston",
  "Southern Methodist University",
  "Baylor University",
  "Texas Christian University",
  "University of Tennessee",
  "University of Kentucky",
  "University of Alabama",
  "Auburn University",
  "Louisiana State University",
  "University of Oklahoma",
  "University of Arkansas",
  "University of Missouri",
  "University of Cincinnati",
  "University of Louisville",
  "Wake Forest University",
  "Lehigh University",
  "Rensselaer Polytechnic Institute",
  "Stevens Institute of Technology",
  "Worcester Polytechnic Institute",
  "Illinois Institute of Technology",
  "Drexel University",
  "Temple University",
  "University of San Diego",
  "Pepperdine University",
  "Santa Clara University",
  "Loyola Marymount University",
  "University of San Francisco",
  "San Diego State University",
  "San Jose State University",
  "California State University, Los Angeles",
  "California State University, Fullerton",
  "California State University, Long Beach",
  "California State University, Northridge",
  "University of Nevada, Las Vegas",
  "University of New Mexico",
  "Colorado State University",
  "University of Denver",
  "Creighton University",
  "Marquette University",
  "DePaul University",
  "Loyola University Chicago",
  "University of Illinois at Chicago",
  "Saint Louis University",
];

// Top UK Universities
const UK_UNIVERSITIES = [
  "University of Oxford",
  "Oxford University",
  "University of Cambridge",
  "Cambridge University",
  "Imperial College London",
  "University College London (UCL)",
  "London School of Economics and Political Science (LSE)",
  "University of Edinburgh",
  "University of Manchester",
  "King's College London",
  "University of Bristol",
  "University of Warwick",
  "University of Glasgow",
  "Durham University",
  "University of Birmingham",
  "University of Southampton",
  "University of Leeds",
  "University of Sheffield",
  "University of Nottingham",
  "Queen Mary University of London",
  "Lancaster University",
  "University of York",
  "University of Exeter",
  "Newcastle University",
  "Cardiff University",
  "Prifysgol Caerdydd", // Welsh
  "University of Bath",
  "University of Liverpool",
  "University of Aberdeen",
  "University of St Andrews",
  "University of Reading",
  "University of Leicester",
  "University of Surrey",
  "Royal Holloway, University of London",
  "Loughborough University",
  "University of Sussex",
  "University of East Anglia",
  "University of Kent",
  "University of Essex",
  "Brunel University London",
  "City, University of London",
  "Aston University",
  "Heriot-Watt University",
  "University of Strathclyde",
  "Queen's University Belfast",
  "University of Dundee",
  "Swansea University",
  "Prifysgol Abertawe", // Welsh
  "Bangor University",
  "Prifysgol Bangor", // Welsh
  "Keele University",
  "University of Hull",
  "University of Portsmouth",
  "University of Plymouth",
  "Coventry University",
  "Oxford Brookes University",
  "Northumbria University",
  "Manchester Metropolitan University",
  "Sheffield Hallam University",
  "Leeds Beckett University",
  "Nottingham Trent University",
  "Birmingham City University",
  "University of the West of England",
];

// Top European Universities (excluding UK) - with native language names
const EUROPEAN_UNIVERSITIES = [
  // Switzerland (German/French)
  "ETH Zurich - Swiss Federal Institute of Technology",
  "ETH Zürich",
  "Eidgenössische Technische Hochschule Zürich",
  "École Polytechnique Fédérale de Lausanne (EPFL)",
  "University of Zurich",
  "Universität Zürich",
  "University of Geneva",
  "Université de Genève",
  "University of Basel",
  "Universität Basel",
  "University of Bern",
  "Universität Bern",
  "University of Lausanne",
  "Université de Lausanne",

  // Germany (German)
  "Technical University of Munich (TUM)",
  "Technische Universität München",
  "Ludwig Maximilian University of Munich (LMU)",
  "Ludwig-Maximilians-Universität München",
  "Heidelberg University",
  "Ruprecht-Karls-Universität Heidelberg",
  "Universität Heidelberg",
  "Humboldt University of Berlin",
  "Humboldt-Universität zu Berlin",
  "Free University of Berlin",
  "Freie Universität Berlin",
  "Technical University of Berlin",
  "Technische Universität Berlin",
  "RWTH Aachen University",
  "RWTH Aachen",
  "Rheinisch-Westfälische Technische Hochschule Aachen",
  "University of Freiburg",
  "Albert-Ludwigs-Universität Freiburg",
  "Universität Freiburg",
  "University of Göttingen",
  "Georg-August-Universität Göttingen",
  "Universität Göttingen",
  "University of Bonn",
  "Rheinische Friedrich-Wilhelms-Universität Bonn",
  "Universität Bonn",
  "University of Hamburg",
  "Universität Hamburg",
  "University of Tübingen",
  "Eberhard Karls Universität Tübingen",
  "Universität Tübingen",
  "University of Cologne",
  "Universität zu Köln",
  "University of Frankfurt",
  "Goethe-Universität Frankfurt am Main",
  "Goethe Universität Frankfurt",
  "Universität Frankfurt",
  "University of Stuttgart",
  "Universität Stuttgart",
  "Karlsruhe Institute of Technology (KIT)",
  "Karlsruher Institut für Technologie",
  "Technical University of Dresden",
  "Technische Universität Dresden",
  "University of Mannheim",
  "Universität Mannheim",
  "University of Münster",
  "Westfälische Wilhelms-Universität Münster",
  "Universität Münster",
  "University of Leipzig",
  "Universität Leipzig",
  "University of Erlangen-Nuremberg",
  "Friedrich-Alexander-Universität Erlangen-Nürnberg",
  "FAU Erlangen-Nürnberg",
  "University of Würzburg",
  "Julius-Maximilians-Universität Würzburg",
  "Universität Würzburg",
  "University of Konstanz",
  "Universität Konstanz",
  "University of Duisburg-Essen",
  "Universität Duisburg-Essen",
  "University of Bremen",
  "Universität Bremen",
  "University of Hannover",
  "Leibniz Universität Hannover",
  "Universität Hannover",
  "University of Kiel",
  "Christian-Albrechts-Universität zu Kiel",
  "Universität Kiel",
  "University of Mainz",
  "Johannes Gutenberg-Universität Mainz",
  "Universität Mainz",
  "University of Marburg",
  "Philipps-Universität Marburg",
  "Universität Marburg",
  "University of Regensburg",
  "Universität Regensburg",
  "University of Ulm",
  "Universität Ulm",
  "University of Bielefeld",
  "Universität Bielefeld",
  "University of Düsseldorf",
  "Heinrich-Heine-Universität Düsseldorf",
  "Universität Düsseldorf",
  "University of Jena",
  "Friedrich-Schiller-Universität Jena",
  "Universität Jena",
  "University of Potsdam",
  "Universität Potsdam",
  "University of Rostock",
  "Universität Rostock",
  "University of Saarland",
  "Universität des Saarlandes",
  "Jacobs University Bremen",

  // France (French)
  "Paris Sciences et Lettres (PSL University)",
  "Université PSL",
  "Sorbonne University",
  "Sorbonne Université",
  "Université Paris-Saclay",
  "École Polytechnique",
  "École Normale Supérieure (ENS Paris)",
  "École Normale Supérieure de Paris",
  "Sciences Po Paris",
  "Institut d'études politiques de Paris",
  "HEC Paris",
  "École des Hautes Études Commerciales de Paris",
  "INSEAD",
  "University of Paris",
  "Université de Paris",
  "Université Paris Cité",
  "Aix-Marseille University",
  "Aix-Marseille Université",
  "University of Strasbourg",
  "Université de Strasbourg",
  "University of Bordeaux",
  "Université de Bordeaux",
  "University of Lyon",
  "Université de Lyon",
  "University of Montpellier",
  "Université de Montpellier",
  "University of Toulouse",
  "Université de Toulouse",
  "Université Toulouse 1 Capitole",
  "University of Grenoble Alpes",
  "Université Grenoble Alpes",
  "University of Lille",
  "Université de Lille",
  "University of Nantes",
  "Université de Nantes",
  "University of Nice Sophia Antipolis",
  "Université Nice Sophia Antipolis",
  "Université Côte d'Azur",
  "University of Rennes",
  "Université de Rennes",
  "CentraleSupélec",
  "École des Ponts ParisTech",
  "École nationale des ponts et chaussées",
  "Mines ParisTech",
  "École nationale supérieure des mines de Paris",
  "ESSEC Business School",
  "ESCP Business School",
  "EDHEC Business School",
  "Toulouse Business School",

  // Netherlands (Dutch)
  "University of Amsterdam",
  "Universiteit van Amsterdam",
  "Delft University of Technology",
  "Technische Universiteit Delft",
  "TU Delft",
  "Eindhoven University of Technology",
  "Technische Universiteit Eindhoven",
  "TU Eindhoven",
  "Utrecht University",
  "Universiteit Utrecht",
  "Leiden University",
  "Universiteit Leiden",
  "University of Groningen",
  "Rijksuniversiteit Groningen",
  "Erasmus University Rotterdam",
  "Erasmus Universiteit Rotterdam",
  "Vrije Universiteit Amsterdam",
  "VU Amsterdam",
  "Wageningen University & Research",
  "Wageningen Universiteit",
  "Maastricht University",
  "Universiteit Maastricht",
  "Radboud University",
  "Radboud Universiteit",
  "Tilburg University",
  "Tilburg Universiteit",
  "University of Twente",
  "Universiteit Twente",

  // Belgium (Dutch/French)
  "KU Leuven",
  "Katholieke Universiteit Leuven",
  "Ghent University",
  "Universiteit Gent",
  "Université Catholique de Louvain (UCLouvain)",
  "Vrije Universiteit Brussel",
  "VUB",
  "University of Antwerp",
  "Universiteit Antwerpen",
  "Université Libre de Bruxelles",
  "ULB",

  // Sweden (Swedish)
  "Karolinska Institute",
  "Karolinska Institutet",
  "KTH Royal Institute of Technology",
  "Kungliga Tekniska högskolan",
  "Lund University",
  "Lunds universitet",
  "Uppsala University",
  "Uppsala universitet",
  "Stockholm University",
  "Stockholms universitet",
  "Chalmers University of Technology",
  "Chalmers tekniska högskola",
  "University of Gothenburg",
  "Göteborgs universitet",
  "Linköping University",
  "Linköpings universitet",
  "Umeå University",
  "Umeå universitet",
  "Stockholm School of Economics",
  "Handelshögskolan i Stockholm",

  // Denmark (Danish)
  "University of Copenhagen",
  "Københavns Universitet",
  "Technical University of Denmark (DTU)",
  "Danmarks Tekniske Universitet",
  "Aarhus University",
  "Aarhus Universitet",
  "University of Southern Denmark",
  "Syddansk Universitet",
  "Aalborg University",
  "Aalborg Universitet",
  "Copenhagen Business School",
  "Handelshøjskolen i København",

  // Norway (Norwegian)
  "University of Oslo",
  "Universitetet i Oslo",
  "Norwegian University of Science and Technology (NTNU)",
  "Norges teknisk-naturvitenskapelige universitet",
  "University of Bergen",
  "Universitetet i Bergen",
  "Norwegian School of Economics",
  "Norges Handelshøyskole",
  "NHH",
  "UiT The Arctic University of Norway",
  "UiT Norges arktiske universitet",

  // Finland (Finnish)
  "University of Helsinki",
  "Helsingin yliopisto",
  "Helsingfors universitet",
  "Aalto University",
  "Aalto-yliopisto",
  "University of Turku",
  "Turun yliopisto",
  "University of Oulu",
  "Oulun yliopisto",
  "Tampere University",
  "Tampereen yliopisto",

  // Austria (German)
  "University of Vienna",
  "Universität Wien",
  "Vienna University of Technology",
  "Technische Universität Wien",
  "TU Wien",
  "University of Innsbruck",
  "Universität Innsbruck",
  "Leopold-Franzens-Universität Innsbruck",
  "Medical University of Vienna",
  "Medizinische Universität Wien",
  "University of Graz",
  "Universität Graz",
  "Karl-Franzens-Universität Graz",
  "Johannes Kepler University Linz",
  "Johannes Kepler Universität Linz",
  "JKU Linz",
  "WU Vienna University of Economics and Business",
  "Wirtschaftsuniversität Wien",
  "WU Wien",

  // Italy (Italian)
  "Politecnico di Milano",
  "University of Bologna",
  "Università di Bologna",
  "Alma Mater Studiorum",
  "Sapienza University of Rome",
  "Sapienza Università di Roma",
  "La Sapienza",
  "University of Milan",
  "Università degli Studi di Milano",
  "Università di Milano",
  "University of Padua",
  "Università degli Studi di Padova",
  "Università di Padova",
  "University of Turin",
  "Università degli Studi di Torino",
  "Università di Torino",
  "University of Pisa",
  "Università di Pisa",
  "University of Florence",
  "Università degli Studi di Firenze",
  "Università di Firenze",
  "University of Naples Federico II",
  "Università degli Studi di Napoli Federico II",
  "Bocconi University",
  "Università Bocconi",
  "Politecnico di Torino",
  "University of Rome Tor Vergata",
  "Università degli Studi di Roma Tor Vergata",
  "University of Genoa",
  "Università degli Studi di Genova",
  "University of Trento",
  "Università degli Studi di Trento",
  "University of Trieste",
  "Università degli Studi di Trieste",
  "Ca' Foscari University of Venice",
  "Università Ca' Foscari Venezia",
  "Catholic University of the Sacred Heart",
  "Università Cattolica del Sacro Cuore",
  "LUISS University",
  "Libera Università Internazionale degli Studi Sociali Guido Carli",
  "Scuola Normale Superiore di Pisa",
  "Scuola Normale Superiore",
  "Sant'Anna School of Advanced Studies",
  "Scuola Superiore Sant'Anna",

  // Spain (Spanish/Catalan)
  "University of Barcelona",
  "Universitat de Barcelona",
  "Universidad de Barcelona",
  "Autonomous University of Barcelona",
  "Universitat Autònoma de Barcelona",
  "UAB",
  "Complutense University of Madrid",
  "Universidad Complutense de Madrid",
  "UCM",
  "Autonomous University of Madrid",
  "Universidad Autónoma de Madrid",
  "UAM",
  "Pompeu Fabra University",
  "Universitat Pompeu Fabra",
  "UPF",
  "University of Valencia",
  "Universitat de València",
  "Universidad de Valencia",
  "University of Granada",
  "Universidad de Granada",
  "University of Seville",
  "Universidad de Sevilla",
  "Polytechnic University of Catalonia",
  "Universitat Politècnica de Catalunya",
  "UPC",
  "Polytechnic University of Madrid",
  "Universidad Politécnica de Madrid",
  "UPM",
  "University of Salamanca",
  "Universidad de Salamanca",
  "University of Navarra",
  "Universidad de Navarra",
  "University of the Basque Country",
  "Universidad del País Vasco",
  "Euskal Herriko Unibertsitatea",
  "University of Zaragoza",
  "Universidad de Zaragoza",
  "Carlos III University of Madrid",
  "Universidad Carlos III de Madrid",
  "UC3M",
  "IE University",
  "IESE Business School",
  "ESADE Business School",

  // Portugal (Portuguese)
  "University of Lisbon",
  "Universidade de Lisboa",
  "University of Porto",
  "Universidade do Porto",
  "University of Coimbra",
  "Universidade de Coimbra",
  "Nova University Lisbon",
  "Universidade Nova de Lisboa",
  "University of Minho",
  "Universidade do Minho",
  "University of Aveiro",
  "Universidade de Aveiro",
  "ISCTE – University Institute of Lisbon",
  "ISCTE – Instituto Universitário de Lisboa",

  // Ireland
  "Trinity College Dublin",
  "Coláiste na Tríonóide",
  "University College Dublin",
  "An Coláiste Ollscoile",
  "National University of Ireland, Galway",
  "Ollscoil na hÉireann, Gaillimh",
  "University College Cork",
  "Coláiste na hOllscoile Corcaigh",
  "Dublin City University",
  "Ollscoil Chathair Bhaile Átha Cliath",
  "Maynooth University",
  "Ollscoil Mhá Nuad",

  // Poland (Polish)
  "University of Warsaw",
  "Uniwersytet Warszawski",
  "Jagiellonian University",
  "Uniwersytet Jagielloński",
  "Warsaw University of Technology",
  "Politechnika Warszawska",
  "AGH University of Science and Technology",
  "Akademia Górniczo-Hutnicza",
  "Adam Mickiewicz University",
  "Uniwersytet im. Adama Mickiewicza w Poznaniu",
  "Wrocław University of Science and Technology",
  "Politechnika Wrocławska",
  "University of Wrocław",
  "Uniwersytet Wrocławski",
  "Gdańsk University of Technology",
  "Politechnika Gdańska",

  // Czech Republic (Czech)
  "Charles University",
  "Univerzita Karlova",
  "Czech Technical University in Prague",
  "České vysoké učení technické v Praze",
  "ČVUT",
  "Masaryk University",
  "Masarykova univerzita",
  "Palacký University Olomouc",
  "Univerzita Palackého v Olomouci",

  // Hungary (Hungarian)
  "Eötvös Loránd University",
  "Eötvös Loránd Tudományegyetem",
  "ELTE",
  "Budapest University of Technology and Economics",
  "Budapesti Műszaki és Gazdaságtudományi Egyetem",
  "BME",
  "University of Szeged",
  "Szegedi Tudományegyetem",
  "Semmelweis University",
  "Semmelweis Egyetem",
  "Central European University",
  "Közép-európai Egyetem",

  // Greece (Greek)
  "National Technical University of Athens",
  "Εθνικό Μετσόβιο Πολυτεχνείο",
  "National and Kapodistrian University of Athens",
  "Εθνικό και Καποδιστριακό Πανεπιστήμιο Αθηνών",
  "Aristotle University of Thessaloniki",
  "Αριστοτέλειο Πανεπιστήμιο Θεσσαλονίκης",
  "University of Crete",
  "Πανεπιστήμιο Κρήτης",
  "University of Patras",
  "Πανεπιστήμιο Πατρών",

  // Russia (Russian)
  "Lomonosov Moscow State University",
  "Московский государственный университет имени М. В. Ломоносова",
  "МГУ",
  "Saint Petersburg State University",
  "Санкт-Петербургский государственный университет",
  "СПбГУ",
  "Moscow Institute of Physics and Technology (MIPT)",
  "Московский физико-технический институт",
  "МФТИ",
  "National Research Nuclear University MEPhI",
  "Национальный исследовательский ядерный университет МИФИ",
  "МИФИ",
  "Novosibirsk State University",
  "Новосибирский государственный университет",
  "НГУ",
  "Higher School of Economics",
  "Высшая школа экономики",
  "ВШЭ",
  "ITMO University",
  "Университет ИТМО",
  "ИТМО",
  "Bauman Moscow State Technical University",
  "Московский государственный технический университет имени Н. Э. Баумана",
  "МГТУ им. Баумана",
  "Peter the Great St. Petersburg Polytechnic University",
  "Санкт-Петербургский политехнический университет Петра Великого",
  "СПбПУ",
  "Kazan Federal University",
  "Казанский федеральный университет",
  "КФУ",
  "Tomsk State University",
  "Томский государственный университет",
  "ТГУ",
  "Ural Federal University",
  "Уральский федеральный университет",
  "УрФУ",
];

// Top Asian Universities - with native language names
const ASIAN_UNIVERSITIES = [
  // China (Chinese Pinyin and characters)
  "Tsinghua University",
  "清华大学",
  "Qinghua Daxue",
  "Peking University",
  "北京大学",
  "Beijing Daxue",
  "Beida",
  "Fudan University",
  "复旦大学",
  "Shanghai Jiao Tong University",
  "上海交通大学",
  "Zhejiang University",
  "浙江大学",
  "University of Science and Technology of China",
  "中国科学技术大学",
  "USTC",
  "Nanjing University",
  "南京大学",
  "Wuhan University",
  "武汉大学",
  "Sun Yat-sen University",
  "中山大学",
  "Zhongshan University",
  "Harbin Institute of Technology",
  "哈尔滨工业大学",
  "Xi'an Jiaotong University",
  "西安交通大学",
  "Tongji University",
  "同济大学",
  "Huazhong University of Science and Technology",
  "华中科技大学",
  "HUST",
  "Tianjin University",
  "天津大学",
  "Beihang University",
  "北京航空航天大学",
  "BUAA",
  "Southeast University",
  "东南大学",
  "Beijing Normal University",
  "北京师范大学",
  "Renmin University of China",
  "中国人民大学",
  "Nankai University",
  "南开大学",
  "Sichuan University",
  "四川大学",
  "Central South University",
  "中南大学",
  "South China University of Technology",
  "华南理工大学",
  "Xiamen University",
  "厦门大学",
  "East China Normal University",
  "华东师范大学",
  "Dalian University of Technology",
  "大连理工大学",
  "Jilin University",
  "吉林大学",
  "Northeastern University (China)",
  "东北大学",
  "Shandong University",
  "山东大学",
  "Beijing Institute of Technology",
  "北京理工大学",
  "University of Electronic Science and Technology of China",
  "电子科技大学",
  "UESTC",
  "Northwestern Polytechnical University",
  "西北工业大学",
  "Chongqing University",
  "重庆大学",
  "Lanzhou University",
  "兰州大学",
  "Ocean University of China",
  "中国海洋大学",
  "China Agricultural University",
  "中国农业大学",
  "Beijing Jiaotong University",
  "北京交通大学",
  "Beijing University of Chemical Technology",
  "北京化工大学",
  "East China University of Science and Technology",
  "华东理工大学",
  "Soochow University",
  "苏州大学",
  "Jiangnan University",
  "江南大学",

  // Hong Kong (Chinese/English)
  "University of Hong Kong",
  "香港大学",
  "HKU",
  "Hong Kong University of Science and Technology",
  "香港科技大学",
  "HKUST",
  "Chinese University of Hong Kong",
  "香港中文大学",
  "CUHK",
  "City University of Hong Kong",
  "香港城市大学",
  "CityU",
  "Hong Kong Polytechnic University",
  "香港理工大学",
  "PolyU",
  "Hong Kong Baptist University",
  "香港浸会大学",
  "HKBU",
  "Lingnan University",
  "岭南大学",

  // Taiwan (Chinese)
  "National Taiwan University",
  "國立臺灣大學",
  "台湾大学",
  "NTU Taiwan",
  "National Tsing Hua University",
  "國立清華大學",
  "NTHU",
  "National Cheng Kung University",
  "國立成功大學",
  "NCKU",
  "National Yang Ming Chiao Tung University",
  "國立陽明交通大學",
  "NYCU",
  "National Chiao Tung University",
  "國立交通大學",
  "NCTU",
  "National Central University",
  "國立中央大學",
  "NCU",
  "National Sun Yat-sen University",
  "國立中山大學",
  "NSYSU",
  "Taipei Medical University",
  "臺北醫學大學",
  "TMU",
  "National Taiwan University of Science and Technology",
  "國立臺灣科技大學",
  "Taiwan Tech",
  "National Chengchi University",
  "國立政治大學",
  "NCCU",

  // Japan (Japanese)
  "University of Tokyo",
  "東京大学",
  "Tōkyō Daigaku",
  "Todai",
  "Kyoto University",
  "京都大学",
  "Kyōto Daigaku",
  "Kyodai",
  "Tokyo Institute of Technology",
  "東京工業大学",
  "Tōkyō Kōgyō Daigaku",
  "Tokyo Tech",
  "Osaka University",
  "大阪大学",
  "Ōsaka Daigaku",
  "Handai",
  "Tohoku University",
  "東北大学",
  "Tōhoku Daigaku",
  "Nagoya University",
  "名古屋大学",
  "Nagoya Daigaku",
  "Meidai",
  "Hokkaido University",
  "北海道大学",
  "Hokkaidō Daigaku",
  "Hokudai",
  "Kyushu University",
  "九州大学",
  "Kyūshū Daigaku",
  "Kyudai",
  "Keio University",
  "慶應義塾大学",
  "Keiō Gijuku Daigaku",
  "Waseda University",
  "早稲田大学",
  "Waseda Daigaku",
  "University of Tsukuba",
  "筑波大学",
  "Tsukuba Daigaku",
  "Kobe University",
  "神戸大学",
  "Kōbe Daigaku",
  "Shindai",
  "Hiroshima University",
  "広島大学",
  "Hiroshima Daigaku",
  "Tokyo Medical and Dental University",
  "東京医科歯科大学",
  "TMDU",
  "Yokohama National University",
  "横浜国立大学",
  "Yokohama Kokuritsu Daigaku",
  "Chiba University",
  "千葉大学",
  "Chiba Daigaku",
  "Kanazawa University",
  "金沢大学",
  "Kanazawa Daigaku",
  "Okayama University",
  "岡山大学",
  "Okayama Daigaku",
  "Niigata University",
  "新潟大学",
  "Niigata Daigaku",
  "Tokyo University of Science",
  "東京理科大学",
  "Tōkyō Rika Daigaku",
  "TUS",
  "Ritsumeikan University",
  "立命館大学",
  "Ritsumeikan Daigaku",
  "Doshisha University",
  "同志社大学",
  "Dōshisha Daigaku",
  "Sophia University",
  "上智大学",
  "Jōchi Daigaku",
  "Meiji University",
  "明治大学",
  "Meiji Daigaku",
  "Rikkyo University",
  "立教大学",
  "Rikkyō Daigaku",
  "Hosei University",
  "法政大学",
  "Hōsei Daigaku",

  // South Korea (Korean)
  "Seoul National University",
  "서울대학교",
  "Seoul Daehakgyo",
  "SNU",
  "KAIST - Korea Advanced Institute of Science and Technology",
  "한국과학기술원",
  "KAIST",
  "Pohang University of Science and Technology (POSTECH)",
  "포항공과대학교",
  "POSTECH",
  "Yonsei University",
  "연세대학교",
  "Yonsei Daehakgyo",
  "Korea University",
  "고려대학교",
  "Goryeo Daehakgyo",
  "Sungkyunkwan University",
  "성균관대학교",
  "SKKU",
  "Hanyang University",
  "한양대학교",
  "Hanyang Daehakgyo",
  "Kyung Hee University",
  "경희대학교",
  "Gyeonghui Daehakgyo",
  "Sogang University",
  "서강대학교",
  "Seogang Daehakgyo",
  "Ewha Womans University",
  "이화여자대학교",
  "Ihwa Yeoja Daehakgyo",
  "Chung-Ang University",
  "중앙대학교",
  "Jungang Daehakgyo",
  "CAU",
  "Hankuk University of Foreign Studies",
  "한국외국어대학교",
  "HUFS",
  "Konkuk University",
  "건국대학교",
  "Geonguk Daehakgyo",
  "Dongguk University",
  "동국대학교",
  "Dongguk Daehakgyo",
  "Inha University",
  "인하대학교",
  "Inha Daehakgyo",
  "Ajou University",
  "아주대학교",
  "Aju Daehakgyo",
  "University of Seoul",
  "서울시립대학교",
  "Seoul Sirip Daehakgyo",
  "Pusan National University",
  "부산대학교",
  "Busan Daehakgyo",
  "PNU",
  "Kyungpook National University",
  "경북대학교",
  "Gyeongbuk Daehakgyo",
  "KNU",

  // Singapore
  "National University of Singapore (NUS)",
  "新加坡国立大学",
  "NUS",
  "Nanyang Technological University (NTU)",
  "南洋理工大学",
  "NTU Singapore",
  "Singapore Management University",
  "新加坡管理大学",
  "SMU",
  "Singapore University of Technology and Design",
  "新加坡科技设计大学",
  "SUTD",

  // Malaysia (Malay)
  "University of Malaya",
  "Universiti Malaya",
  "UM",
  "Universiti Putra Malaysia",
  "UPM",
  "Universiti Kebangsaan Malaysia",
  "UKM",
  "National University of Malaysia",
  "Universiti Sains Malaysia",
  "USM",
  "Universiti Teknologi Malaysia",
  "UTM",
  "Taylor's University",
  "Monash University Malaysia",
  "University of Nottingham Malaysia",

  // Thailand (Thai)
  "Chulalongkorn University",
  "จุฬาลงกรณ์มหาวิทยาลัย",
  "Mahidol University",
  "มหาวิทยาลัยมหิดล",
  "Thammasat University",
  "มหาวิทยาลัยธรรมศาสตร์",
  "Kasetsart University",
  "มหาวิทยาลัยเกษตรศาสตร์",
  "Chiang Mai University",
  "มหาวิทยาลัยเชียงใหม่",
  "King Mongkut's University of Technology Thonburi",
  "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
  "KMUTT",

  // Indonesia (Indonesian)
  "University of Indonesia",
  "Universitas Indonesia",
  "UI",
  "Bandung Institute of Technology",
  "Institut Teknologi Bandung",
  "ITB",
  "Gadjah Mada University",
  "Universitas Gadjah Mada",
  "UGM",
  "Airlangga University",
  "Universitas Airlangga",
  "UNAIR",
  "Bogor Agricultural University",
  "Institut Pertanian Bogor",
  "IPB",
  "Institut Teknologi Sepuluh Nopember",
  "ITS",

  // Philippines
  "University of the Philippines",
  "Unibersidad ng Pilipinas",
  "UP",
  "Ateneo de Manila University",
  "ADMU",
  "De La Salle University",
  "DLSU",
  "University of Santo Tomas",
  "UST",

  // Vietnam (Vietnamese)
  "Vietnam National University, Hanoi",
  "Đại học Quốc gia Hà Nội",
  "VNU Hanoi",
  "Vietnam National University, Ho Chi Minh City",
  "Đại học Quốc gia Thành phố Hồ Chí Minh",
  "VNU-HCM",
  "Hanoi University of Science and Technology",
  "Đại học Bách khoa Hà Nội",
  "HUST Vietnam",
  "Ho Chi Minh City University of Technology",
  "Đại học Bách khoa Thành phố Hồ Chí Minh",

  // India (Hindi)
  "Indian Institute of Technology Bombay (IIT Bombay)",
  "भारतीय प्रौद्योगिकी संस्थान बॉम्बे",
  "IIT Bombay",
  "IITB",
  "Indian Institute of Technology Delhi (IIT Delhi)",
  "भारतीय प्रौद्योगिकी संस्थान दिल्ली",
  "IIT Delhi",
  "IITD",
  "Indian Institute of Technology Madras (IIT Madras)",
  "IIT Madras",
  "IITM",
  "Indian Institute of Technology Kanpur (IIT Kanpur)",
  "IIT Kanpur",
  "IITK",
  "Indian Institute of Technology Kharagpur (IIT Kharagpur)",
  "IIT Kharagpur",
  "IIT KGP",
  "Indian Institute of Technology Roorkee (IIT Roorkee)",
  "IIT Roorkee",
  "IITR",
  "Indian Institute of Technology Guwahati (IIT Guwahati)",
  "IIT Guwahati",
  "IITG",
  "Indian Institute of Technology Hyderabad (IIT Hyderabad)",
  "IIT Hyderabad",
  "IITH",
  "Indian Institute of Technology Indore (IIT Indore)",
  "IIT Indore",
  "Indian Institute of Technology (BHU) Varanasi",
  "IIT BHU",
  "Indian Institute of Science (IISc) Bangalore",
  "भारतीय विज्ञान संस्थान",
  "IISc",
  "University of Delhi",
  "दिल्ली विश्वविद्यालय",
  "DU",
  "Jawaharlal Nehru University",
  "जवाहरलाल नेहरू विश्वविद्यालय",
  "JNU",
  "Jadavpur University",
  "যাদবপুর বিশ্ববিদ্যালয়",
  "JU",
  "University of Calcutta",
  "কলকাতা বিশ্ববিদ্যালয়",
  "CU",
  "University of Mumbai",
  "मुंबई विश्वविद्यालय",
  "Anna University",
  "Savitribai Phule Pune University",
  "SPPU",
  "Banaras Hindu University",
  "BHU",
  "Aligarh Muslim University",
  "AMU",
  "Jamia Millia Islamia",
  "JMI",
  "University of Hyderabad",
  "UoH",
  "Birla Institute of Technology and Science (BITS) Pilani",
  "BITS Pilani",
  "National Institute of Technology (NIT) Tiruchirappalli",
  "NIT Trichy",
  "National Institute of Technology (NIT) Surathkal",
  "NIT Surathkal",
  "NITK",
  "National Institute of Technology (NIT) Warangal",
  "NIT Warangal",
  "NITW",
  "Vellore Institute of Technology",
  "VIT",
  "Manipal Academy of Higher Education",
  "MAHE",
  "Amity University",
  "SRM Institute of Science and Technology",
  "SRMIST",
  "Chandigarh University",
  "Lovely Professional University",
  "LPU",
  "Christ University",
  "Symbiosis International University",
  "Indian Institute of Management Ahmedabad (IIM-A)",
  "IIM Ahmedabad",
  "IIMA",
  "Indian Institute of Management Bangalore (IIM-B)",
  "IIM Bangalore",
  "IIMB",
  "Indian Institute of Management Calcutta (IIM-C)",
  "IIM Calcutta",
  "IIMC",
  "Indian School of Business",
  "ISB",
  "All India Institute of Medical Sciences (AIIMS)",
  "AIIMS Delhi",

  // Pakistan (Urdu)
  "Quaid-i-Azam University",
  "قائداعظم یونیورسٹی",
  "QAU",
  "Lahore University of Management Sciences (LUMS)",
  "لاہور یونیورسٹی آف مینجمنٹ سائنسز",
  "LUMS",
  "National University of Sciences and Technology (NUST)",
  "نیشنل یونیورسٹی آف سائنسز اینڈ ٹیکنالوجی",
  "NUST",
  "COMSATS University Islamabad",
  "کامسیٹس یونیورسٹی اسلام آباد",
  "CUI",
  "University of the Punjab",
  "پنجاب یونیورسٹی",
  "PU",
  "Aga Khan University",
  "AKU",
  "University of Karachi",
  "جامعہ کراچی",
  "KU",
  "University of Engineering and Technology Lahore",
  "یونیورسٹی آف انجینئرنگ اینڈ ٹیکنالوجی",
  "UET Lahore",

  // Bangladesh (Bengali)
  "University of Dhaka",
  "ঢাকা বিশ্ববিদ্যালয়",
  "DU Bangladesh",
  "Bangladesh University of Engineering and Technology",
  "বাংলাদেশ প্রকৌশল বিশ্ববিদ্যালয়",
  "BUET",
  "North South University",
  "NSU",
  "BRAC University",
  "ব্র্যাক বিশ্ববিদ্যালয়",
];

// Middle East Universities (excluding Iran) - with native language names
const MIDDLE_EAST_UNIVERSITIES = [
  // Israel (Hebrew)
  "Hebrew University of Jerusalem",
  "האוניברסיטה העברית בירושלים",
  "HUJI",
  "Tel Aviv University",
  "אוניברסיטת תל אביב",
  "TAU",
  "Technion - Israel Institute of Technology",
  "הטכניון – מכון טכנולוגי לישראל",
  "Technion",
  "Weizmann Institute of Science",
  "מכון ויצמן למדע",
  "Ben-Gurion University of the Negev",
  "אוניברסיטת בן-גוריון בנגב",
  "BGU",
  "Bar-Ilan University",
  "אוניברסיטת בר-אילן",
  "BIU",
  "University of Haifa",
  "אוניברסיטת חיפה",

  // Turkey (Turkish)
  "Koç University",
  "Koç Üniversitesi",
  "Bilkent University",
  "Bilkent Üniversitesi",
  "Sabancı University",
  "Sabancı Üniversitesi",
  "Middle East Technical University",
  "Orta Doğu Teknik Üniversitesi",
  "ODTÜ",
  "METU",
  "Boğaziçi University",
  "Boğaziçi Üniversitesi",
  "Istanbul Technical University",
  "İstanbul Teknik Üniversitesi",
  "İTÜ",
  "Ankara University",
  "Ankara Üniversitesi",
  "Istanbul University",
  "İstanbul Üniversitesi",
  "Hacettepe University",
  "Hacettepe Üniversitesi",
  "Ege University",
  "Ege Üniversitesi",
  "Dokuz Eylül University",
  "Dokuz Eylül Üniversitesi",
  "Yıldız Technical University",
  "Yıldız Teknik Üniversitesi",
  "YTÜ",
  "Marmara University",
  "Marmara Üniversitesi",
  "Gazi University",
  "Gazi Üniversitesi",

  // Saudi Arabia (Arabic)
  "King Abdullah University of Science and Technology (KAUST)",
  "جامعة الملك عبدالله للعلوم والتقنية",
  "KAUST",
  "King Saud University",
  "جامعة الملك سعود",
  "KSU",
  "King Abdulaziz University",
  "جامعة الملك عبدالعزيز",
  "KAU",
  "King Fahd University of Petroleum and Minerals",
  "جامعة الملك فهد للبترول والمعادن",
  "KFUPM",
  "Alfaisal University",
  "جامعة الفيصل",
  "Prince Sultan University",
  "جامعة الأمير سلطان",
  "PSU",
  "Umm Al-Qura University",
  "جامعة أم القرى",
  "UQU",
  "King Khalid University",
  "جامعة الملك خالد",
  "KKU",

  // United Arab Emirates (Arabic)
  "Khalifa University",
  "جامعة خليفة",
  "KU",
  "United Arab Emirates University",
  "جامعة الإمارات العربية المتحدة",
  "UAEU",
  "American University of Sharjah",
  "الجامعة الأمريكية في الشارقة",
  "AUS",
  "University of Sharjah",
  "جامعة الشارقة",
  "UoS",
  "New York University Abu Dhabi",
  "جامعة نيويورك أبوظبي",
  "NYUAD",
  "American University in Dubai",
  "الجامعة الأمريكية في دبي",
  "AUD",
  "Zayed University",
  "جامعة زايد",
  "ZU",

  // Qatar (Arabic)
  "Qatar University",
  "جامعة قطر",
  "QU",
  "Hamad Bin Khalifa University",
  "جامعة حمد بن خليفة",
  "HBKU",
  "Carnegie Mellon University in Qatar",
  "جامعة كارنيجي ميلون في قطر",
  "CMU-Q",
  "Georgetown University in Qatar",
  "جامعة جورجتاون في قطر",
  "GU-Q",
  "Northwestern University in Qatar",
  "جامعة نورث وسترن في قطر",
  "NU-Q",
  "Texas A&M University at Qatar",
  "جامعة تكساس إيه آند إم في قطر",
  "TAMUQ",

  // Lebanon (Arabic/French)
  "American University of Beirut",
  "الجامعة الأميركية في بيروت",
  "AUB",
  "Lebanese American University",
  "الجامعة اللبنانية الأميركية",
  "LAU",
  "Université Saint-Joseph de Beyrouth",
  "جامعة القديس يوسف",
  "USJ",
  "Lebanese University",
  "الجامعة اللبنانية",
  "Université Libanaise",
  "LU",

  // Jordan (Arabic)
  "University of Jordan",
  "الجامعة الأردنية",
  "UJ",
  "Jordan University of Science and Technology",
  "جامعة العلوم والتكنولوجيا الأردنية",
  "JUST",
  "German Jordanian University",
  "الجامعة الألمانية الأردنية",
  "GJU",
  "American University of Madaba",
  "الجامعة الأمريكية في مادبا",

  // Egypt (Arabic)
  "Cairo University",
  "جامعة القاهرة",
  "CU",
  "American University in Cairo",
  "الجامعة الأمريكية بالقاهرة",
  "AUC",
  "Ain Shams University",
  "جامعة عين شمس",
  "ASU",
  "Alexandria University",
  "جامعة الإسكندرية",
  "AU Egypt",
  "Mansoura University",
  "جامعة المنصورة",
  "Assiut University",
  "جامعة أسيوط",

  // Kuwait (Arabic)
  "Kuwait University",
  "جامعة الكويت",
  "KU Kuwait",
  "Gulf University for Science and Technology",
  "جامعة الخليج للعلوم والتكنولوجيا",
  "GUST",
  "American University of Kuwait",
  "الجامعة الأمريكية في الكويت",
  "AUK",

  // Oman (Arabic)
  "Sultan Qaboos University",
  "جامعة السلطان قابوس",
  "SQU",
  "German University of Technology in Oman",
  "الجامعة الألمانية للتكنولوجيا في عُمان",
  "GUtech",

  // Bahrain (Arabic)
  "University of Bahrain",
  "جامعة البحرين",
  "UoB",
  "Arabian Gulf University",
  "جامعة الخليج العربي",
  "AGU",
];

// Iranian Universities (Comprehensive list) - with Persian/Farsi names
const IRANIAN_UNIVERSITIES = [
  // Top Research Universities
  "University of Tehran",
  "دانشگاه تهران",
  "Daneshgah-e Tehran",
  "UT",
  "Sharif University of Technology",
  "دانشگاه صنعتی شریف",
  "Daneshgah-e Sanati-ye Sharif",
  "Sharif",
  "SUT",
  "Amirkabir University of Technology (Tehran Polytechnic)",
  "دانشگاه صنعتی امیرکبیر",
  "Daneshgah-e Sanati-ye Amirkabir",
  "Amirkabir",
  "AUT",
  "Polytechnic Tehran",
  "Iran University of Science and Technology",
  "دانشگاه علم و صنعت ایران",
  "Daneshgah-e Elm-o-Sanat-e Iran",
  "IUST",
  "Shiraz University",
  "دانشگاه شیراز",
  "Daneshgah-e Shiraz",
  "Isfahan University of Technology",
  "دانشگاه صنعتی اصفهان",
  "Daneshgah-e Sanati-ye Isfahan",
  "IUT",
  "Ferdowsi University of Mashhad",
  "دانشگاه فردوسی مشهد",
  "Daneshgah-e Ferdowsi-ye Mashhad",
  "FUM",
  "Tarbiat Modares University",
  "دانشگاه تربیت مدرس",
  "Daneshgah-e Tarbiat Modares",
  "TMU",
  "K. N. Toosi University of Technology",
  "دانشگاه صنعتی خواجه نصیرالدین طوسی",
  "Daneshgah-e Sanati-ye Khaje Nasir",
  "KNTU",
  "Khaje Nasir",
  "Tehran University of Medical Sciences",
  "دانشگاه علوم پزشکی تهران",
  "Daneshgah-e Olum Pezeshki Tehran",
  "TUMS",
  "Shahid Beheshti University",
  "دانشگاه شهید بهشتی",
  "Daneshgah-e Shahid Beheshti",
  "SBU",
  "Shahid Beheshti University of Medical Sciences",
  "دانشگاه علوم پزشکی شهید بهشتی",
  "SBMU",
  "Isfahan University of Medical Sciences",
  "دانشگاه علوم پزشکی اصفهان",
  "MUI",
  "Shiraz University of Medical Sciences",
  "دانشگاه علوم پزشکی شیراز",
  "SUMS",
  "Mashhad University of Medical Sciences",
  "دانشگاه علوم پزشکی مشهد",
  "MUMS",
  "Tabriz University of Medical Sciences",
  "دانشگاه علوم پزشکی تبریز",
  "TBZMED",

  // Major Public Universities
  "University of Tabriz",
  "دانشگاه تبریز",
  "Daneshgah-e Tabriz",
  "Tabriz University",
  "Bu-Ali Sina University",
  "دانشگاه بوعلی سینا",
  "Daneshgah-e Bu-Ali Sina",
  "BASU",
  "University of Guilan",
  "دانشگاه گیلان",
  "Daneshgah-e Gilan",
  "Guilan University",
  "University of Mazandaran",
  "دانشگاه مازندران",
  "Daneshgah-e Mazandaran",
  "UMZ",
  "Urmia University",
  "دانشگاه ارومیه",
  "Daneshgah-e Urmiye",
  "University of Kashan",
  "دانشگاه کاشان",
  "Daneshgah-e Kashan",
  "University of Sistan and Baluchestan",
  "دانشگاه سیستان و بلوچستان",
  "Daneshgah-e Sistan va Baluchestan",
  "USB",
  "University of Kurdistan",
  "دانشگاه کردستان",
  "Daneshgah-e Kordestan",
  "UOK",
  "University of Birjand",
  "دانشگاه بیرجند",
  "Daneshgah-e Birjand",
  "Shahrekord University",
  "دانشگاه شهرکرد",
  "Daneshgah-e Shahrekord",
  "SKU",
  "Ilam University",
  "دانشگاه ایلام",
  "Daneshgah-e Ilam",
  "University of Zanjan",
  "دانشگاه زنجان",
  "Daneshgah-e Zanjan",
  "ZNU",
  "Lorestan University",
  "دانشگاه لرستان",
  "Daneshgah-e Lorestan",
  "LU Iran",
  "University of Hormozgan",
  "دانشگاه هرمزگان",
  "Daneshgah-e Hormozgan",
  "Semnan University",
  "دانشگاه سمنان",
  "Daneshgah-e Semnan",
  "Qom University",
  "دانشگاه قم",
  "Daneshgah-e Qom",
  "University of Mohaghegh Ardabili",
  "دانشگاه محقق اردبیلی",
  "Daneshgah-e Mohaghegh Ardabili",
  "UMA",
  "University of Bojnord",
  "دانشگاه بجنورد",
  "Daneshgah-e Bojnurd",
  "University of Zabol",
  "دانشگاه زابل",
  "Daneshgah-e Zabol",
  "Gonbad Kavous University",
  "دانشگاه گنبد کاووس",
  "Daneshgah-e Gonbad-e Kavus",
  "GKU",
  "Shahrood University of Technology",
  "دانشگاه صنعتی شاهرود",
  "Daneshgah-e Sanati-ye Shahrood",
  "SHAHROODUT",
  "University of Maragheh",
  "دانشگاه مراغه",
  "Daneshgah-e Maragheh",
  "Kharazmi University",
  "دانشگاه خوارزمی",
  "Daneshgah-e Kharazmi",
  "KHU",
  "Alzahra University",
  "دانشگاه الزهرا",
  "Daneshgah-e Alzahra",
  "ALZAHRA",
  "Allameh Tabataba'i University",
  "دانشگاه علامه طباطبائی",
  "Daneshgah-e Allameh Tabataba'i",
  "ATU",
  "University of Social Welfare and Rehabilitation Sciences",
  "دانشگاه علوم بهزیستی و توانبخشی",
  "USWR",
  "Imam Khomeini International University",
  "دانشگاه بین‌المللی امام خمینی",
  "Daneshgah-e Beinolmelali Imam Khomeini",
  "IKIU",
  "Shahid Chamran University of Ahvaz",
  "دانشگاه شهید چمران اهواز",
  "Daneshgah-e Shahid Chamran",
  "SCU",
  "Shahid Bahonar University of Kerman",
  "دانشگاه شهید باهنر کرمان",
  "Daneshgah-e Shahid Bahonar",
  "UK",
  "Yazd University",
  "دانشگاه یزد",
  "Daneshgah-e Yazd",
  "YU",
  "Razi University",
  "دانشگاه رازی",
  "Daneshgah-e Razi",
  "Arak University",
  "دانشگاه اراک",
  "Daneshgah-e Arak",
  "University of Qom",
  "دانشگاه قم",
  "Hakim Sabzevari University",
  "دانشگاه حکیم سبزواری",
  "Daneshgah-e Hakim Sabzevari",
  "HSU",
  "Vali-e-Asr University of Rafsanjan",
  "دانشگاه ولیعصر رفسنجان",
  "Daneshgah-e Valiasr",
  "VRU",
  "Persian Gulf University",
  "دانشگاه خلیج فارس",
  "Daneshgah-e Khalij-e Fars",
  "PGU",
  "Jahrom University",
  "دانشگاه جهرم",
  "Daneshgah-e Jahrom",
  "Damghan University",
  "دانشگاه دامغان",
  "Daneshgah-e Damghan",
  "Malayer University",
  "دانشگاه ملایر",
  "Daneshgah-e Malayer",
  "University of Neyshabur",
  "دانشگاه نیشابور",
  "Daneshgah-e Neyshabur",

  // Technical Universities
  "Sahand University of Technology",
  "دانشگاه صنعتی سهند",
  "Daneshgah-e Sanati-ye Sahand",
  "SUT Tabriz",
  "Babol Noshirvani University of Technology",
  "دانشگاه صنعتی نوشیروانی بابل",
  "Daneshgah-e Sanati-ye Noshirvani Babol",
  "NITU",
  "Urmia University of Technology",
  "دانشگاه صنعتی ارومیه",
  "Daneshgah-e Sanati-ye Urmiye",
  "UUT",
  "Kermanshah University of Technology",
  "دانشگاه صنعتی کرمانشاه",
  "Daneshgah-e Sanati-ye Kermanshah",
  "KUT",
  "Sirjan University of Technology",
  "دانشگاه صنعتی سیرجان",
  "Daneshgah-e Sanati-ye Sirjan",
  "Quchan University of Technology",
  "دانشگاه صنعتی قوچان",
  "Daneshgah-e Sanati-ye Quchan",
  "QUT",
  "Hamedan University of Technology",
  "دانشگاه صنعتی همدان",
  "Daneshgah-e Sanati-ye Hamedan",
  "HUT",
  "Birjand University of Technology",
  "دانشگاه صنعتی بیرجند",
  "Daneshgah-e Sanati-ye Birjand",

  // Medical Universities
  "Iran University of Medical Sciences",
  "دانشگاه علوم پزشکی ایران",
  "Daneshgah-e Olum Pezeshki Iran",
  "IUMS",
  "Ahvaz Jundishapur University of Medical Sciences",
  "دانشگاه علوم پزشکی جندی شاپور اهواز",
  "AJUMS",
  "Kerman University of Medical Sciences",
  "دانشگاه علوم پزشکی کرمان",
  "KMU",
  "Hamadan University of Medical Sciences",
  "دانشگاه علوم پزشکی همدان",
  "UMSHA",
  "Babol University of Medical Sciences",
  "دانشگاه علوم پزشکی بابل",
  "MUBABOL",
  "Urmia University of Medical Sciences",
  "دانشگاه علوم پزشکی ارومیه",
  "UMSU",
  "Arak University of Medical Sciences",
  "دانشگاه علوم پزشکی اراک",
  "ARAKMU",
  "Kurdistan University of Medical Sciences",
  "دانشگاه علوم پزشکی کردستان",
  "MUK",
  "Yazd University of Medical Sciences",
  "دانشگاه علوم پزشکی یزد",
  "SSU",
  "Qazvin University of Medical Sciences",
  "دانشگاه علوم پزشکی قزوین",
  "QUMS",
  "Semnan University of Medical Sciences",
  "دانشگاه علوم پزشکی سمنان",
  "SEMUMS",
  "Ilam University of Medical Sciences",
  "دانشگاه علوم پزشکی ایلام",
  "MEDILAM",
  "Ardabil University of Medical Sciences",
  "دانشگاه علوم پزشکی اردبیل",
  "ARUMS",
  "Zanjan University of Medical Sciences",
  "دانشگاه علوم پزشکی زنجان",
  "ZUMS",
  "Rafsanjan University of Medical Sciences",
  "دانشگاه علوم پزشکی رفسنجان",
  "RUMS",
  "Bushehr University of Medical Sciences",
  "دانشگاه علوم پزشکی بوشهر",
  "BPUMS",
  "North Khorasan University of Medical Sciences",
  "دانشگاه علوم پزشکی خراسان شمالی",
  "NKUMS",
  "South Khorasan University of Medical Sciences",
  "دانشگاه علوم پزشکی خراسان جنوبی",
  "BUMS",
  "Lorestan University of Medical Sciences",
  "دانشگاه علوم پزشکی لرستان",
  "LUMS Iran",
  "Golestan University of Medical Sciences",
  "دانشگاه علوم پزشکی گلستان",
  "GOUMS",
  "Baqiyatallah University of Medical Sciences",
  "دانشگاه علوم پزشکی بقیه الله",
  "BMSU",
  "AJA University of Medical Sciences",
  "دانشگاه علوم پزشکی ارتش",
  "AJAUMS",

  // Islamic Azad University Branches (Major ones)
  "Islamic Azad University",
  "دانشگاه آزاد اسلامی",
  "Daneshgah-e Azad-e Eslami",
  "IAU",
  "Islamic Azad University, Science and Research Branch",
  "دانشگاه آزاد اسلامی واحد علوم و تحقیقات",
  "Daneshgah-e Azad Olum va Tahghighat",
  "IAU SRB",
  "Islamic Azad University, Tehran South Branch",
  "دانشگاه آزاد اسلامی واحد تهران جنوب",
  "Islamic Azad University, Tehran North Branch",
  "دانشگاه آزاد اسلامی واحد تهران شمال",
  "Islamic Azad University, Tehran Central Branch",
  "دانشگاه آزاد اسلامی واحد تهران مرکز",
  "Islamic Azad University, Karaj Branch",
  "دانشگاه آزاد اسلامی واحد کرج",
  "Islamic Azad University, Shiraz Branch",
  "دانشگاه آزاد اسلامی واحد شیراز",
  "Islamic Azad University, Isfahan Branch (Khorasgan)",
  "دانشگاه آزاد اسلامی واحد اصفهان (خوراسگان)",
  "دانشگاه آزاد خوراسگان",
  "Islamic Azad University, Tabriz Branch",
  "دانشگاه آزاد اسلامی واحد تبریز",
  "Islamic Azad University, Mashhad Branch",
  "دانشگاه آزاد اسلامی واحد مشهد",
  "Islamic Azad University, Najafabad Branch",
  "دانشگاه آزاد اسلامی واحد نجف‌آباد",
  "Islamic Azad University, Qazvin Branch",
  "دانشگاه آزاد اسلامی واحد قزوین",
  "QIAU",
  "Islamic Azad University, Rasht Branch",
  "دانشگاه آزاد اسلامی واحد رشت",
  "Islamic Azad University, Yazd Branch",
  "دانشگاه آزاد اسلامی واحد یزد",
  "Islamic Azad University, Kerman Branch",
  "دانشگاه آزاد اسلامی واحد کرمان",
  "Islamic Azad University, Ahvaz Branch",
  "دانشگاه آزاد اسلامی واحد اهواز",
  "Islamic Azad University, Arak Branch",
  "دانشگاه آزاد اسلامی واحد اراک",
  "Islamic Azad University, Hamadan Branch",
  "دانشگاه آزاد اسلامی واحد همدان",
  "Islamic Azad University, Sanandaj Branch",
  "دانشگاه آزاد اسلامی واحد سنندج",
  "Islamic Azad University, Urmia Branch",
  "دانشگاه آزاد اسلامی واحد ارومیه",
  "Islamic Azad University, Zanjan Branch",
  "دانشگاه آزاد اسلامی واحد زنجان",
  "Islamic Azad University, Semnan Branch",
  "دانشگاه آزاد اسلامی واحد سمنان",
  "Islamic Azad University, Qom Branch",
  "دانشگاه آزاد اسلامی واحد قم",
  "Islamic Azad University, Bandar Abbas Branch",
  "دانشگاه آزاد اسلامی واحد بندرعباس",
  "Islamic Azad University, Gorgan Branch",
  "دانشگاه آزاد اسلامی واحد گرگان",
  "Islamic Azad University, Sari Branch",
  "دانشگاه آزاد اسلامی واحد ساری",

  // Payame Noor University (Main campuses)
  "Payame Noor University (PNU)",
  "دانشگاه پیام نور",
  "Daneshgah-e Payam-e Noor",
  "PNU",
  "Payame Noor University, Tehran",
  "دانشگاه پیام نور تهران",
  "Payame Noor University, Mashhad",
  "دانشگاه پیام نور مشهد",
  "Payame Noor University, Isfahan",
  "دانشگاه پیام نور اصفهان",
  "Payame Noor University, Tabriz",
  "دانشگاه پیام نور تبریز",
  "Payame Noor University, Shiraz",
  "دانشگاه پیام نور شیراز",

  // Specialized Universities
  "Institute for Advanced Studies in Basic Sciences (IASBS)",
  "پژوهشگاه دانش‌های بنیادی",
  "IASBS",
  "Institute for Research in Fundamental Sciences (IPM)",
  "پژوهشگاه دانش‌های بنیادی",
  "IPM",
  "National Research Institute for Science Policy",
  "پژوهشکده سیاست‌گذاری علم و فناوری",
  "NRISP",
  "Petroleum University of Technology",
  "دانشگاه صنعت نفت",
  "Daneshgah-e Sanat-e Naft",
  "PUT",
  "University of Art",
  "دانشگاه هنر",
  "Daneshgah-e Honar",
  "Iran Broadcasting University",
  "دانشگاه صدا و سیما",
  "IRIBU",
  "University of Police",
  "دانشگاه علوم انتظامی امین",
  "Amin Police University",
  "Imam Sadiq University",
  "دانشگاه امام صادق",
  "Daneshgah-e Imam Sadegh",
  "ISU",
  "University of Religions and Denominations",
  "دانشگاه ادیان و مذاهب",
  "URD",
  "Farhangian University",
  "دانشگاه فرهنگیان",
  "Daneshgah-e Farhangian",
  "Shahid Rajaee Teacher Training University",
  "دانشگاه تربیت دبیر شهید رجایی",
  "SRTTU",
  "Technical and Vocational University",
  "دانشگاه فنی و حرفه‌ای",
  "TVU",

  // Private Universities
  "Sharif University of Technology, Kish Island",
  "دانشگاه صنعتی شریف کیش",
  "Khatam University",
  "دانشگاه خاتم",
  "Daneshgah-e Khatam",
  "Imam Reza International University",
  "دانشگاه بین‌المللی امام رضا",
  "IMAMREZA",
  "Shahed University",
  "دانشگاه شاهد",
  "Daneshgah-e Shahed",
  "University of Science and Culture",
  "دانشگاه علم و فرهنگ",
  "Daneshgah-e Elm-o-Farhang",
  "UAST",
];

// Australia & New Zealand Universities
const OCEANIA_UNIVERSITIES = [
  // Australia
  "University of Melbourne",
  "University of Sydney",
  "Australian National University",
  "University of Queensland",
  "University of New South Wales (UNSW)",
  "Monash University",
  "University of Western Australia",
  "University of Adelaide",
  "University of Technology Sydney",
  "Macquarie University",
  "Queensland University of Technology",
  "RMIT University",
  "Curtin University",
  "University of Wollongong",
  "Deakin University",
  "University of Newcastle",
  "Griffith University",
  "La Trobe University",
  "James Cook University",
  "Swinburne University of Technology",
  "Flinders University",
  "University of Tasmania",
  "Charles Darwin University",
  "Western Sydney University",
  "Victoria University",
  "Bond University",
  "Australian Catholic University",
  "University of South Australia",
  "University of Canberra",
  "Central Queensland University",
  "Southern Cross University",
  "University of New England",
  "Edith Cowan University",
  "Murdoch University",
  "University of the Sunshine Coast",
  "Charles Sturt University",
  "Federation University Australia",

  // New Zealand
  "University of Auckland",
  "University of Otago",
  "Victoria University of Wellington",
  "University of Canterbury",
  "Massey University",
  "University of Waikato",
  "Lincoln University",
  "Auckland University of Technology",
];

// African Universities
const AFRICAN_UNIVERSITIES = [
  // South Africa
  "University of Cape Town",
  "University of the Witwatersrand",
  "Stellenbosch University",
  "University of Pretoria",
  "University of KwaZulu-Natal",
  "University of Johannesburg",
  "Rhodes University",
  "University of the Western Cape",
  "North-West University",
  "University of the Free State",

  // Egypt (already in Middle East, adding remaining)
  "Zagazig University",
  "Helwan University",
  "Suez Canal University",

  // Nigeria
  "University of Ibadan",
  "University of Lagos",
  "Obafemi Awolowo University",
  "Ahmadu Bello University",
  "University of Nigeria",
  "Covenant University",

  // Morocco
  "Mohammed V University",
  "Cadi Ayyad University",
  "Hassan II University of Casablanca",

  // Tunisia
  "University of Tunis El Manar",
  "University of Sfax",

  // Kenya
  "University of Nairobi",
  "Kenyatta University",
  "Strathmore University",

  // Ghana
  "University of Ghana",
  "Kwame Nkrumah University of Science and Technology",

  // Algeria
  "University of Algiers",
  "University of Science and Technology Houari Boumediene",

  // Ethiopia
  "Addis Ababa University",

  // Tanzania
  "University of Dar es Salaam",

  // Uganda
  "Makerere University",
];

// Latin American Universities - with native language names (Spanish/Portuguese)
const LATIN_AMERICAN_UNIVERSITIES = [
  // Brazil (Portuguese)
  "University of São Paulo (USP)",
  "Universidade de São Paulo",
  "USP",
  "University of Campinas (UNICAMP)",
  "Universidade Estadual de Campinas",
  "UNICAMP",
  "Federal University of Rio de Janeiro (UFRJ)",
  "Universidade Federal do Rio de Janeiro",
  "UFRJ",
  "Federal University of Minas Gerais (UFMG)",
  "Universidade Federal de Minas Gerais",
  "UFMG",
  "Federal University of Rio Grande do Sul (UFRGS)",
  "Universidade Federal do Rio Grande do Sul",
  "UFRGS",
  "São Paulo State University (UNESP)",
  "Universidade Estadual Paulista",
  "UNESP",
  "Pontifical Catholic University of Rio de Janeiro (PUC-Rio)",
  "Pontifícia Universidade Católica do Rio de Janeiro",
  "PUC-Rio",
  "Pontifical Catholic University of São Paulo (PUC-SP)",
  "Pontifícia Universidade Católica de São Paulo",
  "PUC-SP",
  "Federal University of São Paulo (UNIFESP)",
  "Universidade Federal de São Paulo",
  "UNIFESP",
  "Federal University of Santa Catarina (UFSC)",
  "Universidade Federal de Santa Catarina",
  "UFSC",
  "Federal University of Paraná (UFPR)",
  "Universidade Federal do Paraná",
  "UFPR",
  "Federal University of Pernambuco (UFPE)",
  "Universidade Federal de Pernambuco",
  "UFPE",
  "Federal University of Bahia (UFBA)",
  "Universidade Federal da Bahia",
  "UFBA",
  "Federal University of Ceará (UFC)",
  "Universidade Federal do Ceará",
  "UFC",
  "Fluminense Federal University (UFF)",
  "Universidade Federal Fluminense",
  "UFF",

  // Mexico (Spanish)
  "National Autonomous University of Mexico (UNAM)",
  "Universidad Nacional Autónoma de México",
  "UNAM",
  "Monterrey Institute of Technology (ITESM/Tec de Monterrey)",
  "Instituto Tecnológico y de Estudios Superiores de Monterrey",
  "Tecnológico de Monterrey",
  "Tec de Monterrey",
  "ITESM",
  "Instituto Politécnico Nacional",
  "IPN",
  "Universidad Iberoamericana",
  "IBERO",
  "Universidad Panamericana",
  "UP Mexico",
  "Universidad de Guadalajara",
  "UdeG",
  "Universidad Autónoma de Nuevo León",
  "UANL",
  "Universidad Autónoma Metropolitana",
  "UAM Mexico",
  "CINVESTAV",
  "Centro de Investigación y de Estudios Avanzados",
  "El Colegio de México",
  "COLMEX",

  // Argentina (Spanish)
  "University of Buenos Aires",
  "Universidad de Buenos Aires",
  "UBA",
  "Pontifical Catholic University of Argentina",
  "Pontificia Universidad Católica Argentina",
  "UCA Argentina",
  "National University of Córdoba",
  "Universidad Nacional de Córdoba",
  "UNC Argentina",
  "University of Belgrano",
  "Universidad de Belgrano",
  "Austral University",
  "Universidad Austral",
  "Instituto Tecnológico de Buenos Aires",
  "ITBA",
  "National University of La Plata",
  "Universidad Nacional de La Plata",
  "UNLP",
  "National University of Rosario",
  "Universidad Nacional de Rosario",
  "UNR",

  // Chile (Spanish)
  "Pontifical Catholic University of Chile",
  "Pontificia Universidad Católica de Chile",
  "PUC Chile",
  "UC Chile",
  "University of Chile",
  "Universidad de Chile",
  "UCH",
  "Universidad de Santiago de Chile",
  "USACH",
  "Universidad de Concepción",
  "UdeC",
  "Universidad Adolfo Ibáñez",
  "UAI",
  "Universidad Diego Portales",
  "UDP",

  // Colombia (Spanish)
  "University of the Andes, Colombia",
  "Universidad de los Andes",
  "Uniandes",
  "National University of Colombia",
  "Universidad Nacional de Colombia",
  "UNAL",
  "Pontifical Javeriana University",
  "Pontificia Universidad Javeriana",
  "PUJ",
  "Universidad del Rosario",
  "URosario",
  "Universidad del Norte",
  "Uninorte",
  "Universidad EAFIT",
  "EAFIT",

  // Peru (Spanish)
  "Pontifical Catholic University of Peru",
  "Pontificia Universidad Católica del Perú",
  "PUCP",
  "National University of San Marcos",
  "Universidad Nacional Mayor de San Marcos",
  "UNMSM",
  "San Marcos",
  "Universidad Peruana Cayetano Heredia",
  "UPCH",
  "Universidad de Lima",
  "ULima",

  // Venezuela (Spanish)
  "Central University of Venezuela",
  "Universidad Central de Venezuela",
  "UCV",
  "Universidad Simón Bolívar",
  "USB Venezuela",

  // Ecuador (Spanish)
  "Universidad San Francisco de Quito",
  "USFQ",
  "Escuela Politécnica Nacional",
  "EPN",

  // Costa Rica (Spanish)
  "University of Costa Rica",
  "Universidad de Costa Rica",
  "UCR",
  "Costa Rica Institute of Technology",
  "Instituto Tecnológico de Costa Rica",
  "TEC Costa Rica",
];

// Canadian Universities - with French names for Quebec institutions
const CANADIAN_UNIVERSITIES = [
  "University of Toronto",
  "U of T",
  "UofT",
  "University of British Columbia",
  "UBC",
  "McGill University",
  "Université McGill",
  "McMaster University",
  "Mac",
  "University of Montreal",
  "Université de Montréal",
  "UdeM",
  "University of Alberta",
  "UAlberta",
  "U of A",
  "University of Waterloo",
  "UWaterloo",
  "Waterloo",
  "Western University",
  "University of Western Ontario",
  "UWO",
  "University of Ottawa",
  "Université d'Ottawa",
  "uOttawa",
  "University of Calgary",
  "UCalgary",
  "U of C",
  "Queen's University",
  "Queen's",
  "Simon Fraser University",
  "SFU",
  "Dalhousie University",
  "Dal",
  "University of Manitoba",
  "UManitoba",
  "U of M",
  "University of Saskatchewan",
  "USask",
  "University of Victoria",
  "UVic",
  "York University",
  "YorkU",
  "Carleton University",
  "Concordia University",
  "Université Concordia",
  "Laval University",
  "Université Laval",
  "University of Guelph",
  "Ryerson University / Toronto Metropolitan University",
  "Toronto Metropolitan University",
  "TMU",
  "Memorial University of Newfoundland",
  "MUN",
  "University of Windsor",
  "UWindsor",
  "University of Regina",
  "U of R",
  "Brock University",
  "Wilfrid Laurier University",
  "Laurier",
  "WLU",
  "University of New Brunswick",
  "UNB",
  "University of Lethbridge",
  "ULethbridge",
  "Saint Mary's University",
  "SMU",
  "Lakehead University",
  "Trent University",
  "Laurentian University",
  "Université Laurentienne",
  "UQAM - Université du Québec à Montréal",
  "Université du Québec à Montréal",
  "UQAM",
  "University of Sherbrooke",
  "Université de Sherbrooke",
  "UdeS",
  "École Polytechnique de Montréal",
  "Polytechnique Montréal",
  "HEC Montréal",
  "HEC Montreal",
  "École de technologie supérieure",
  "ÉTS",
  "ETS Montreal",
  "INRS - Institut national de la recherche scientifique",
  "Institut national de la recherche scientifique",
  "INRS",
  "Université du Québec",
  "UQTR - Université du Québec à Trois-Rivières",
  "UQAC - Université du Québec à Chicoutimi",
  "UQO - Université du Québec en Outaouais",
  "UQAR - Université du Québec à Rimouski",
  "UQAT - Université du Québec en Abitibi-Témiscamingue",
  "TÉLUQ",
  "Bishop's University",
];

// Combine all universities into a single array
const ALL_UNIVERSITIES = [
  ...US_UNIVERSITIES,
  ...UK_UNIVERSITIES,
  ...EUROPEAN_UNIVERSITIES,
  ...ASIAN_UNIVERSITIES,
  ...MIDDLE_EAST_UNIVERSITIES,
  ...IRANIAN_UNIVERSITIES,
  ...OCEANIA_UNIVERSITIES,
  ...AFRICAN_UNIVERSITIES,
  ...LATIN_AMERICAN_UNIVERSITIES,
  ...CANADIAN_UNIVERSITIES,
];

interface InstitutionAutocompleteProps {
  value: string;
  onChange: (value: string) => void;
  onSave?: () => void;
  onCancel?: () => void;
  placeholder?: string;
  label?: string;
  fullWidth?: boolean;
  disabled?: boolean;
  error?: boolean;
  helperText?: string;
  sx?: any;
  // Writing correction props
  fieldCorrection?: FieldCorrection | null;
  correctionImportance?: 'highly_recommended' | 'standard';
  correctionReasoning?: string;
  onApplyCorrection?: (correction: FieldCorrection) => void;
  onDismissCorrection?: () => void;
}

const InstitutionAutocomplete: React.FC<InstitutionAutocompleteProps> = ({
  value,
  onChange,
  onSave,
  onCancel,
  placeholder = "e.g., University of California",
  label = "Institution",
  fullWidth = true,
  disabled = false,
  error = false,
  helperText,
  sx,
  fieldCorrection,
  correctionImportance,
  correctionReasoning,
  onApplyCorrection,
  onDismissCorrection,
}) => {
  const [inputValue, setInputValue] = useState(value);
  const [isOpen, setIsOpen] = useState(false);

  // Resync the displayed input when the `value` prop changes externally
  // (e.g. an AI correction updates it, or this instance is reused for a
  // different item via index-key reuse). Without this, the initial seed
  // from `value` would go stale.
  useEffect(() => {
    setInputValue(value);
  }, [value]);

  // Filter institutions based on input
  const filteredInstitutions = useMemo(() => {
    if (!inputValue || inputValue.length < 2) return [];

    const searchTerm = inputValue.toLowerCase().trim();
    const searchWords = searchTerm.split(/\s+/);

    // Filter with multiple criteria for better matching
    const filtered = ALL_UNIVERSITIES.filter((institution) => {
      const institutionLower = institution.toLowerCase();

      // All search words must be present
      const allWordsMatch = searchWords.every(word => institutionLower.includes(word));
      if (allWordsMatch) return true;

      // Starts with search term (high priority)
      if (institutionLower.startsWith(searchTerm)) return true;

      // Contains search term (medium priority)
      if (institutionLower.includes(searchTerm)) return true;

      // Abbreviation match (for cases like "MIT" matching "Massachusetts Institute of Technology")
      const abbreviation = institutionLower.match(/\(([^)]+)\)/)?.[1];
      if (abbreviation && abbreviation.includes(searchTerm)) return true;

      return false;
    });

    // Sort results by relevance
    const sorted = filtered.sort((a, b) => {
      const aLower = a.toLowerCase();
      const bLower = b.toLowerCase();

      // Exact matches first
      if (aLower === searchTerm && bLower !== searchTerm) return -1;
      if (bLower === searchTerm && aLower !== searchTerm) return 1;

      // Then starts with
      if (aLower.startsWith(searchTerm) && !bLower.startsWith(searchTerm)) return -1;
      if (bLower.startsWith(searchTerm) && !aLower.startsWith(searchTerm)) return 1;

      // Then prioritize shorter names (more likely to be exact matches)
      return a.length - b.length;
    });

    return sorted.slice(0, 15); // Limit to 15 suggestions for better UX
  }, [inputValue]);

  const handleChange = (_event: any, newValue: string | null) => {
    const selectedValue = newValue || "";
    setInputValue(selectedValue);
    onChange(selectedValue);
    setIsOpen(false);
  };

  const handleInputChange = (_event: any, newInputValue: string) => {
    setInputValue(newInputValue);
    onChange(newInputValue);
    setIsOpen(newInputValue.length >= 2);
  };

  const handleFocus = () => {
    if (inputValue.length >= 2) {
      const exactMatch = ALL_UNIVERSITIES.find(
        (institution) => institution.toLowerCase() === inputValue.toLowerCase().trim(),
      );
      setIsOpen(!exactMatch);
    } else {
      setIsOpen(false);
    }
  };

  const handleBlur = () => {
    setTimeout(() => {
      setIsOpen(false);
    }, 150);
  };

  const handleKeyDown = (event: React.KeyboardEvent) => {
    if (event.key === "Enter") {
      event.preventDefault();
      setIsOpen(false);
      if (onSave) {
        onSave();
      }
    } else if (event.key === "Escape") {
      event.preventDefault();
      setIsOpen(false);
      if (onCancel) {
        onCancel();
      }
    }
  };

  return (
    <Box>
      <Autocomplete
        value={value}
        onChange={handleChange}
        inputValue={inputValue}
        onInputChange={handleInputChange}
        options={filteredInstitutions}
        freeSolo
        handleHomeEndKeys
        open={isOpen}
        renderInput={(params) => (
          <TextField
            {...params}
            label={label}
            placeholder={placeholder}
            fullWidth={fullWidth}
            disabled={disabled}
            error={error}
            helperText={helperText}
            variant="standard"
            onKeyDown={handleKeyDown}
            onFocus={handleFocus}
            onBlur={handleBlur}
            sx={{
              ...sx,
            }}
          />
        )}
        renderOption={(props, option, { index }) => (
          <li {...props} key={`${option}-${index}`}>
            {option}
          </li>
        )}
        noOptionsText="Type at least 2 characters to search..."
        sx={{
          "& .MuiAutocomplete-inputRoot": {
            paddingTop: 0,
            paddingBottom: 0,
          },
          ...sx,
        }}
      />
      {fieldCorrection && correctionImportance && (
        <InlineFieldCorrection
          fieldCorrection={fieldCorrection}
          importance={correctionImportance}
          reasoning={correctionReasoning}
          onApply={() => onApplyCorrection?.(fieldCorrection)}
          onDismiss={onDismissCorrection || (() => {})}
        />
      )}
    </Box>
  );
};

export default InstitutionAutocomplete;
