"""
HTML diff cleaning utilities.

Provides functions to clean and normalize html_diff strings generated by AI,
fixing formatting issues, and derive computed fields from html_diff.
"""

import logging
import re
from typing import Dict, Any, Optional
from src.services.ai_service.writing_corrections_service import apply_html_diff

logger = logging.getLogger(__name__)


def clean_html_diff_string(html_diff: str) -> str:
    """
    Clean html_diff string to fix formatting issues.

    Fixes:
    - Literal \\n escape sequences → actual newline characters
    - Empty <del></del> tags (removes them to prevent visual indentation)

    Preserves:
    - Valid HTML syntax
    - Unicode characters

    Args:
        html_diff: Raw html_diff string from AI

    Returns:
        Cleaned html_diff string
    """
    if not html_diff or not isinstance(html_diff, str):
        return html_diff

    result = html_diff

    # Convert literal \n escape sequences to actual newlines
    # AI generates strings with literal "\n" (backslash + n) that need to be converted
    # to actual newline characters for proper rendering
    result = result.replace("\\n", "\n")

    # Remove empty <del></del> tags (common when original is empty)
    # Prevents visual indentation from empty deleted tags
    result = re.sub(r"<del></del>", "", result)

    return result


def extract_original_from_cv_data(
    response: Dict[str, Any],
    cv_data: Dict[str, Any],
    id_mapping: Optional[Dict[str, Dict[str, str]]] = None,
) -> Dict[str, Any]:
    """
    Extract original values from CV data for work experience, education, and field corrections.

    The AI response contains items with item_id (short IDs like "1", "2", "3") but no original field.
    This function:
    1. Maps short IDs back to actual IDs using id_mapping
    2. Looks up each item in cv_data using actual_id and section
    3. Extracts the description field to populate original

    For writing_corrections, it also extracts original_value for each field_correction
    by looking up the field value in the CV data.

    Args:
        response: AI response dictionary with work_experience, education, and writing_corrections
        cv_data: Original CV data dictionary containing the actual item data
        id_mapping: Optional dictionary mapping section names to {short_id: actual_id} mappings.
                   If provided, short IDs in response are mapped back to actual IDs before lookup.

    Returns:
        Modified response dictionary with original and original_value fields populated,
        and item_ids converted from short IDs to actual IDs
    """
    if not response or not isinstance(response, dict):
        return response

    # Map short IDs back to actual IDs if mapping is provided
    if id_mapping:
        # Map work_experience IDs
        for item in response.get("work_experience", []):
            if isinstance(item, dict) and "item_id" in item:
                short_id = item["item_id"]
                if "work_experience" in id_mapping:
                    actual_id = id_mapping["work_experience"].get(short_id)
                    if actual_id:
                        item["item_id"] = actual_id

        # Map education IDs
        for item in response.get("education", []):
            if isinstance(item, dict) and "item_id" in item:
                short_id = item["item_id"]
                if "education" in id_mapping:
                    actual_id = id_mapping["education"].get(short_id)
                    if actual_id:
                        item["item_id"] = actual_id

        # Map writing_corrections IDs
        for correction in response.get("writing_corrections", []):
            if isinstance(correction, dict) and "item_id" in correction:
                short_id = correction["item_id"]
                section = correction.get("section")
                if section in id_mapping:
                    actual_id = id_mapping[section].get(short_id)
                    if actual_id:
                        correction["item_id"] = actual_id

        # Map content_coaching IDs
        for coaching in response.get("content_coaching", []):
            if isinstance(coaching, dict) and "item_id" in coaching:
                short_id = coaching["item_id"]
                section = coaching.get("section")
                if section in id_mapping:
                    actual_id = id_mapping[section].get(short_id)
                    if actual_id:
                        coaching["item_id"] = actual_id

    # Process work_experience items (all items need original field)
    for item in response.get("work_experience", []):
        if isinstance(item, dict) and "item_id" in item:
            item_id = item["item_id"]
            # Find matching item in CV data
            work_items = cv_data.get("work_experience", [])
            for cv_item in work_items:
                if isinstance(cv_item, dict) and cv_item.get("id") == item_id:
                    # Extract description field (or empty string if missing)
                    item["original"] = cv_item.get("description", "") or ""
                    break
            else:
                # Item not found in CV data, set empty string
                logger.warning(
                    f"Item {item_id} not found in work_experience CV data, setting original to empty"
                )
                item["original"] = ""

    # Process education items (all items need original field)
    for item in response.get("education", []):
        if isinstance(item, dict) and "item_id" in item:
            item_id = item["item_id"]
            # Find matching item in CV data
            education_items = cv_data.get("education", [])
            for cv_item in education_items:
                if isinstance(cv_item, dict) and cv_item.get("id") == item_id:
                    # Extract description field (or empty string if missing)
                    item["original"] = cv_item.get("description", "") or ""
                    break
            else:
                # Item not found in CV data, set empty string
                logger.warning(
                    f"Item {item_id} not found in education CV data, setting original to empty"
                )
                item["original"] = ""

    # Process writing_corrections to extract original_value for field_corrections
    for correction in response.get("writing_corrections", []):
        if not isinstance(correction, dict):
            continue

        item_id = correction.get("item_id")
        section = correction.get("section")

        if not item_id or not section:
            continue

        # Find the item in CV data
        cv_item = None
        if section == "professional_summary":
            cv_item = cv_data.get("professional_summary", {})
        elif section in ("personal_info", "personal_info.description"):
            # AI sometimes returns "personal_info.description"; treat same as "personal_info"
            cv_item = cv_data.get("personal_info", {})
        elif section in ["work_experience", "education"]:
            items = cv_data.get(section, [])
            for item in items:
                if isinstance(item, dict) and item.get("id") == item_id:
                    cv_item = item
                    break

        if not cv_item:
            logger.warning(
                f"Item {item_id} not found in {section}, cannot extract field values"
            )
            # Set empty original_value for all field_corrections
            for field_corr in correction.get("field_corrections", []):
                if isinstance(field_corr, dict):
                    field_corr["original_value"] = ""
            continue

        # Extract original_value for each field_correction
        for field_corr in correction.get("field_corrections", []):
            if not isinstance(field_corr, dict):
                continue

            field_name = field_corr.get("field_name")
            if not field_name:
                field_corr["original_value"] = ""
                continue

            # Extract value from cv_item
            original_value = cv_item.get(field_name, "") or ""
            field_corr["original_value"] = original_value

    return response


def clean_quality_response(response: Dict[str, Any]) -> Dict[str, Any]:
    """
    Post-process AI response to clean html_diff strings, fix formatting issues,
    and derive computed fields (corrected_value, suggested, suggested_text) from html_diff.

    Recursively processes all html_diff fields in:
    - writing_corrections[].field_corrections[].html_diff
    - writing_corrections[].html_diff (deprecated, but still exists)
    - professional_summary.html_diff
    - work_experience[].html_diff (for low_score items)
    - education[].html_diff (for low_score items)

    Also computes derived fields:
    - field_corrections[].corrected_value from html_diff
    - low_score items[].suggested from html_diff (requires original field, which is extracted from CV data in post-processing)
    - professional_summary.suggested_text from html_diff

    Note: The `original` field for work_experience and education items is extracted
    from CV data in post-processing (not generated by AI), and must be present
    before calling this function.

    Args:
        response: AI response dictionary with original fields already populated from CV data

    Returns:
        Cleaned response dictionary with computed fields added
    """
    if not response or not isinstance(response, dict):
        return response

    # Clean and compute fields for writing corrections
    for correction in response.get("writing_corrections", []):
        if not isinstance(correction, dict):
            continue

        # Clean and compute fields for field corrections
        for field_corr in correction.get("field_corrections", []):
            if isinstance(field_corr, dict) and "html_diff" in field_corr:
                # Clean html_diff string
                field_corr["html_diff"] = clean_html_diff_string(field_corr["html_diff"])
                # Compute corrected_value from html_diff
                if "original_value" in field_corr:
                    field_corr["corrected_value"] = apply_html_diff(
                        field_corr["original_value"], field_corr["html_diff"]
                    )

        # Clean deprecated top-level html_diff
        if "html_diff" in correction and correction["html_diff"]:
            correction["html_diff"] = clean_html_diff_string(correction["html_diff"])

    # Clean and compute fields for professional summary
    if "professional_summary" in response and response["professional_summary"]:
        ps = response["professional_summary"]
        if isinstance(ps, dict) and "html_diff" in ps and ps["html_diff"]:
            # Clean html_diff string
            ps["html_diff"] = clean_html_diff_string(ps["html_diff"])
            # Compute suggested_text from html_diff
            if "original_text" in ps:
                ps["suggested_text"] = apply_html_diff(
                    ps["original_text"], ps["html_diff"]
                )

    # Clean and compute fields for work experience and education
    for item in response.get("work_experience", []) + response.get("education", []):
        if isinstance(item, dict) and "html_diff" in item and item["html_diff"]:
            # Clean html_diff string
            item["html_diff"] = clean_html_diff_string(item["html_diff"])
            # Compute suggested from html_diff
            if "original" in item:
                item["suggested"] = apply_html_diff(item["original"], item["html_diff"])

    return response
