"""
HTML diff cleaning utilities.

Provides functions to clean and normalize html_diff strings generated by AI,
fixing formatting issues, and derive computed fields from html_diff.
"""

import logging
import re
from typing import Dict, Any, Optional
from src.services.ai_service.writing_corrections_service import apply_html_diff

logger = logging.getLogger(__name__)


def clean_html_diff_string(html_diff: str) -> str:
    """
    Clean html_diff string to fix formatting issues.

    Fixes:
    - Literal \\n escape sequences → actual newline characters
    - Empty <del></del> tags (removes them to prevent visual indentation)

    Preserves:
    - Valid HTML syntax
    - Unicode characters

    Args:
        html_diff: Raw html_diff string from AI

    Returns:
        Cleaned html_diff string
    """
    if not html_diff or not isinstance(html_diff, str):
        return html_diff

    result = html_diff

    # Convert literal \n escape sequences to actual newlines
    # AI generates strings with literal "\n" (backslash + n) that need to be converted
    # to actual newline characters for proper rendering
    result = result.replace("\\n", "\n")

    # Remove empty <del></del> tags (common when original is empty)
    # Prevents visual indentation from empty deleted tags
    result = re.sub(r"<del></del>", "", result)

    return result


def extract_original_from_cv_data_issues(
    response: Dict[str, Any],
    cv_data: Dict[str, Any],
    id_mapping: Optional[Dict[str, Dict[str, str]]] = None,
) -> Dict[str, Any]:
    """
    Map item_ids in issues and populate original from cv_data (cv_review_v2 shape).

    When response has "issues", maps short IDs to actual IDs using id_mapping and
    sets "original" on each issue with section work_experience/education from the
    corresponding CV item's description.

    For skills issues, extracts the original skill name from CV data.
    """
    if not response or not isinstance(response, dict):
        return response
    issues = response.get("issues")
    if not isinstance(issues, list):
        return response

    for issue in issues:
        if not isinstance(issue, dict):
            continue
        field_path = issue.get("field_path")
        item_id = issue.get("item_id")
        item_type = issue.get("item_type")
        base_section = (field_path or "").split(".")[0] if field_path else ""
        # id_mapping uses section names without array index (e.g. "work_experience", not "work_experience[1]")
        section_key = (
            base_section.split("[")[0]
            if base_section and "[" in base_section
            else base_section
        )

        if id_mapping and item_id and section_key in id_mapping:
            actual_id = id_mapping[section_key].get(item_id)
            if actual_id:
                issue["item_id"] = actual_id
            item_id = issue.get("item_id")

        if field_path and field_path.startswith("work_experience") and item_id:
            work_items = cv_data.get("work_experience", [])
            for cv_item in work_items:
                if isinstance(cv_item, dict) and cv_item.get("id") == item_id:
                    issue["original"] = cv_item.get("description", "") or ""
                    break
            else:
                logger.warning(
                    "Item %s not found in work_experience CV data, setting original to empty",
                    item_id,
                )
                issue["original"] = ""

        elif field_path and field_path.startswith("education") and item_id:
            education_items = cv_data.get("education", [])
            for cv_item in education_items:
                if isinstance(cv_item, dict) and cv_item.get("id") == item_id:
                    issue["original"] = cv_item.get("description", "") or ""
                    break
            else:
                logger.warning(
                    "Item %s not found in education CV data, setting original to empty",
                    item_id,
                )
                issue["original"] = ""

        elif item_type == "skills" and field_path:
            skill_type = _skill_type_from_field_path(field_path)
            if skill_type:
                skills_data = cv_data.get("skills", {})
                skill_list = skills_data.get(skill_type, [])
                if isinstance(skill_list, list):
                    original_skill, _ = _extract_skill_from_html_diff(
                        issue.get("html_diff") or ""
                    )
                    if original_skill is not None:
                        for skill in skill_list:
                            if (
                                isinstance(skill, str)
                                and skill.lower() == original_skill.lower()
                            ):
                                issue["original"] = skill
                                break
                        else:
                            issue["original"] = original_skill
                    else:
                        issue["original"] = None

        elif item_type == "professional_summary":
            summary_obj = cv_data.get("professional_summary") or {}
            issue["original"] = summary_obj.get("content", "") or ""

    return response


def fill_skill_originals_from_cv_data(
    response: Dict[str, Any],
    cv_data: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    Derive missing 'original' on skill suggestions from CV data.

    When the model omits 'original' (to save tokens), match each suggestion's
    'skill' against the CV's technical/soft lists (case-insensitive). If exactly
    one CV skill matches, set original to that CV string (correction). Otherwise
    leave original as None (new suggestion).

    Modifies response in place; also returns response.
    """
    if not response or not isinstance(response, dict) or not cv_data:
        return response
    skills_obj = response.get("skills")
    if not isinstance(skills_obj, dict):
        return response
    cv_skills = cv_data.get("skills") or {}
    if not isinstance(cv_skills, dict):
        return response

    for skill_type in ("technical", "soft"):
        skill_list = skills_obj.get(skill_type)
        if not isinstance(skill_list, list):
            continue
        cv_list = cv_skills.get(skill_type) or []
        if not isinstance(cv_list, list):
            continue
        # Build set of normalized CV skill strings for lookup; keep first exact CV string per normalized form
        cv_normalized_to_original: Dict[str, str] = {}
        for s in cv_list:
            if isinstance(s, str) and s.strip():
                key = s.strip().lower()
                if key not in cv_normalized_to_original:
                    cv_normalized_to_original[key] = s.strip()

        for item in skill_list:
            if not isinstance(item, dict):
                continue
            if item.get("original") not in (None, ""):
                continue
            suggested = item.get("skill")
            if not isinstance(suggested, str) or not suggested.strip():
                continue
            key = suggested.strip().lower()
            if key in cv_normalized_to_original:
                item["original"] = cv_normalized_to_original[key]

    return response


def _skill_type_from_field_path(field_path: str) -> Optional[str]:
    """
    Return "technical" or "soft" if field_path is skills.technical or skills.soft
    (with optional [index]); otherwise None.
    """
    if not field_path or "." not in field_path:
        return None
    segment = field_path.split(".")[-1]
    if "[" in segment:
        segment = segment.split("[")[0]
    return segment if segment in ("technical", "soft") else None


def _extract_skill_from_html_diff(html_diff: str) -> tuple[Optional[str], Optional[str]]:
    """
    Extract original and suggested skill names from html_diff.

    Returns:
        Tuple of (original_skill, suggested_skill) or (None, None) if not found
    """
    if not html_diff:
        return None, None

    # Extract <del> content as original
    del_match = re.search(r"<del>([^<]*)</del>", html_diff)
    original = del_match.group(1).strip() if del_match else None

    # Extract <ins> content as suggested
    ins_match = re.search(r"<ins>([^<]*)</ins>", html_diff)
    suggested = ins_match.group(1).strip() if ins_match else None

    return original, suggested


def clean_quality_response_issues(
    response: Dict[str, Any], cv_data: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """
    Clean html_diff in issues and compute suggested/suggested_text (cv_review_v2).

    Cleans each issue's html_diff; for issues with "original" sets "suggested".
    Converts skills issues into skills.technical/soft format.
    Does not add a top-level professional_summary; the frontend derives
    professional summary suggestions from the issues array only (single source
    of truth).
    """
    if not response or not isinstance(response, dict):
        return response
    issues = response.get("issues")
    if not isinstance(issues, list):
        return response

    # Initialize skills object if not present
    if "skills" not in response:
        response["skills"] = {"technical": [], "soft": []}
    elif not isinstance(response["skills"], dict):
        response["skills"] = {"technical": [], "soft": []}
    if "technical" not in response["skills"]:
        response["skills"]["technical"] = []
    if "soft" not in response["skills"]:
        response["skills"]["soft"] = []

    for issue in issues:
        if not isinstance(issue, dict):
            continue
        html_diff = issue.get("html_diff")
        item_type = issue.get("item_type")
        field_path = issue.get("field_path")

        if html_diff:
            issue["html_diff"] = clean_html_diff_string(html_diff)
            if issue.get("original") is not None:
                issue["suggested"] = apply_html_diff(
                    issue["original"], issue["html_diff"]
                )

        # Convert skills issues to skills.technical/soft format
        if item_type == "skills" and field_path and html_diff:
            skill_type = _skill_type_from_field_path(field_path)
            if skill_type:
                original_skill, suggested_skill = _extract_skill_from_html_diff(html_diff)
                if issue.get("original") is not None:
                    original_skill = issue["original"]
                if suggested_skill:
                    # Check for duplicates (case-insensitive)
                    existing_skills = [
                        s.get("skill", "").lower()
                        for s in response["skills"][skill_type]
                        if isinstance(s, dict)
                    ]

                    if suggested_skill.lower() not in existing_skills:
                        # Create skill suggestion object
                        skill_suggestion = {
                            "skill": suggested_skill,
                            "reasoning": issue.get("reasoning", ""),
                            "original": original_skill if original_skill else None,
                        }

                        # Add to appropriate skills array
                        response["skills"][skill_type].append(skill_suggestion)

    return response
