"""
HTML diff cleaning utilities.

Provides functions to clean and normalize html_diff strings generated by AI,
fixing formatting issues, and derive computed fields from html_diff.
"""

import re
from typing import Dict, Any
from src.services.ai_service.writing_corrections_service import apply_html_diff


def clean_html_diff_string(html_diff: str) -> str:
    """
    Clean html_diff string to fix formatting issues.

    Fixes:
    - Literal \\n escape sequences → actual newline characters

    Preserves:
    - Valid HTML syntax
    - Unicode characters

    Args:
        html_diff: Raw html_diff string from AI

    Returns:
        Cleaned html_diff string
    """
    if not html_diff or not isinstance(html_diff, str):
        return html_diff

    result = html_diff

    # Convert literal \n escape sequences to actual newlines
    # AI generates strings with literal "\n" (backslash + n) that need to be converted
    # to actual newline characters for proper rendering
    result = result.replace("\\n", "\n")

    return result


def clean_quality_response(response: Dict[str, Any]) -> Dict[str, Any]:
    """
    Post-process AI response to clean html_diff strings, fix formatting issues,
    and derive computed fields (corrected_value, suggested, suggested_text) from html_diff.

    Recursively processes all html_diff fields in:
    - writing_corrections[].field_corrections[].html_diff
    - writing_corrections[].html_diff (deprecated, but still exists)
    - professional_summary.html_diff
    - work_experience[].html_diff (for low_score items)
    - education[].html_diff (for low_score items)

    Also computes derived fields:
    - field_corrections[].corrected_value from html_diff
    - low_score items[].suggested from html_diff
    - professional_summary.suggested_text from html_diff

    Args:
        response: Raw AI response dictionary

    Returns:
        Cleaned response dictionary with computed fields added
    """
    if not response or not isinstance(response, dict):
        return response

    # Clean and compute fields for writing corrections
    for correction in response.get("writing_corrections", []):
        if not isinstance(correction, dict):
            continue

        # Clean and compute fields for field corrections
        for field_corr in correction.get("field_corrections", []):
            if isinstance(field_corr, dict) and "html_diff" in field_corr:
                # Clean html_diff string
                field_corr["html_diff"] = clean_html_diff_string(field_corr["html_diff"])
                # Compute corrected_value from html_diff
                if "original_value" in field_corr:
                    field_corr["corrected_value"] = apply_html_diff(
                        field_corr["original_value"], field_corr["html_diff"]
                    )

        # Clean deprecated top-level html_diff
        if "html_diff" in correction and correction["html_diff"]:
            correction["html_diff"] = clean_html_diff_string(correction["html_diff"])

    # Clean and compute fields for professional summary
    if "professional_summary" in response and response["professional_summary"]:
        ps = response["professional_summary"]
        if isinstance(ps, dict) and "html_diff" in ps and ps["html_diff"]:
            # Clean html_diff string
            ps["html_diff"] = clean_html_diff_string(ps["html_diff"])
            # Compute suggested_text from html_diff
            if "original_text" in ps:
                ps["suggested_text"] = apply_html_diff(
                    ps["original_text"], ps["html_diff"]
                )

    # Clean and compute fields for work experience and education
    for item in response.get("work_experience", []) + response.get("education", []):
        if (
            isinstance(item, dict)
            and item.get("item_type") == "low_score"
            and "html_diff" in item
            and item["html_diff"]
        ):
            # Clean html_diff string
            item["html_diff"] = clean_html_diff_string(item["html_diff"])
            # Compute suggested from html_diff
            if "original" in item:
                item["suggested"] = apply_html_diff(item["original"], item["html_diff"])

    return response
