"""
Markdown diff cleaning utilities.

Provides functions to clean and normalize markdown_diff strings generated by AI,
fixing whitespace issues that break markdown rendering.
"""

import re
from typing import Dict, Any


def clean_markdown_diff_string(markdown_diff: str) -> str:
    """
    Clean markdown_diff string to fix whitespace issues that break rendering.

    Fixes:
    - Trailing space before closing strikethrough: `~~text ~~` → `~~text~~`
    - Leading space after opening strikethrough: `~~ text~~` → `~~text~~`
    - Empty strikethrough markers: `~~ ~~` → removed
    - Multiple spaces: `~~text   ~~` → `~~text~~`

    Preserves:
    - Valid markdown syntax: `~~text~~` stays unchanged
    - Intentional spaces in content: `~~text with spaces~~` stays as-is
    - Unicode characters

    Args:
        markdown_diff: Raw markdown_diff string from AI

    Returns:
        Cleaned markdown_diff string
    """
    if not markdown_diff or not isinstance(markdown_diff, str):
        return markdown_diff

    result = markdown_diff

    # Remove empty strikethrough markers (~~ ~~ or ~~   ~~)
    result = re.sub(r"~~\s+~~", "", result)

    # Fix trailing space before closing strikethrough: ~~text ~~ → ~~text~~
    # This pattern matches ~~ followed by content (non-greedy), then whitespace, then ~~
    result = re.sub(r"~~([^~]+?)\s+~~", r"~~\1~~", result)

    # Fix leading space after opening strikethrough: ~~ text~~ → ~~text~~
    # This pattern matches ~~ followed by whitespace, then content, then ~~
    result = re.sub(r"~~\s+([^~]+?)~~", r"~~\1~~", result)

    return result


def clean_quality_response(response: Dict[str, Any]) -> Dict[str, Any]:
    """
    Post-process AI response to clean markdown_diff strings and fix formatting issues.

    Recursively processes all markdown_diff fields in:
    - writing_corrections[].field_corrections[].markdown_diff
    - writing_corrections[].markdown_diff (deprecated, but still exists)
    - professional_summary.markdown_diff
    - work_experience[].markdown_diff (for low_score items)
    - education[].markdown_diff (for low_score items)

    Args:
        response: Raw AI response dictionary

    Returns:
        Cleaned response dictionary
    """
    if not response or not isinstance(response, dict):
        return response

    # Clean writing corrections
    for correction in response.get("writing_corrections", []):
        if not isinstance(correction, dict):
            continue

        # Clean field corrections
        for field_corr in correction.get("field_corrections", []):
            if isinstance(field_corr, dict) and "markdown_diff" in field_corr:
                field_corr["markdown_diff"] = clean_markdown_diff_string(
                    field_corr["markdown_diff"]
                )

        # Clean deprecated top-level markdown_diff
        if "markdown_diff" in correction and correction["markdown_diff"]:
            correction["markdown_diff"] = clean_markdown_diff_string(
                correction["markdown_diff"]
            )

    # Clean professional summary markdown_diff
    if "professional_summary" in response and response["professional_summary"]:
        ps = response["professional_summary"]
        if isinstance(ps, dict) and "markdown_diff" in ps and ps["markdown_diff"]:
            ps["markdown_diff"] = clean_markdown_diff_string(ps["markdown_diff"])

    # Clean work experience and education markdown_diff
    for item in response.get("work_experience", []) + response.get("education", []):
        if (
            isinstance(item, dict)
            and item.get("item_type") == "low_score"
            and "markdown_diff" in item
            and item["markdown_diff"]
        ):
            item["markdown_diff"] = clean_markdown_diff_string(item["markdown_diff"])

    return response
